services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image: vindictive/dsci-522-individual-assignment-quarto-python:test123
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
