services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image: vindictive/dsci-522-individual-assignment-quarto-python:latest
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
